### ISSUE TITLE
citation

### ISSUE THREAD

**Issue by JunMa11** [shruti-jadon/Semantic-Segmentation-Loss-Functions#1]
Dear @shruti-jadon ,

Thanks for your great work, and I very enjoy reading your paper.

It would be highly appreciated if you could add this paper in your reference.
```
@article{SegLossOdyssey,
  title={Segmentation Loss Odyssey},
  author={Ma Jun},
  journal={arXiv preprint arXiv:2005.13449},
  year={2020}
}

```

Kindest regards,
Jun

**Comment by shruti-jadon** [comment]
Good Work, Jun. Yes, I will definitely add your work as a reference on GitHub and cite it on my papers.

**Comment by JunMa11** [comment]
Thank you very much.
